### ISSUE TITLE
Handle the situation where the flag reaches a base 

### ISSUE THREAD

**Issue by corentinartaud** [Luna-Interactive/catastrophe#22]
Dependent on #11, #24 

When a player reaches their base with the flag, the winning screen should appear. After an arbitrary time or after pressing a button, the game should go to the launch menu.

**Comment by stevau5** [comment]
Can I work on this? @mjimenez98

**Comment by mjimenez98** [comment]
@stevau5 Definitely! Just in case, check with @corentinartaud for the UI, and with @i5un for any info related to the player taking the flag.

**Comment by mjimenez98** [comment]
Closed in #105
