### ISSUE TITLE
Create the map scene

### ISSUE THREAD

**Issue by corentinartaud** [Luna-Interactive/catastrophe#4]
This map should be a basic plain terrain, just a starting point so the rest of the team can start working on their areas.

Obstacles can be left for another iteration of the map.

Below is a sketch to serve as a guide.

<img width="646" alt="Screen Shot 2019-10-09 at 1 40 49 AM" src="https://user-images.githubusercontent.com/18094006/66454531-1603eb80-ea36-11e9-98be-28bc1ee99ff8.png">

**Comment by mjimenez98** [comment]
Due to the great progress achieved today, @lyonelz96 and I will push for a PR a bit more ambitious. As of today, the triangle has been constructed using assets. We will work on the ground and the obstacles next.
