### ISSUE TITLE
Flag disappears when grabbing animation is cut short

### ISSUE THREAD

**Issue by mjimenez98** [Luna-Interactive/catastrophe#64]
**Describe the bug**
Flag disappears from the player's screen when grabbing it and not holding `E` for the full length of its animation. Other players in the game see the actor holding the flag as it should be.

**To Reproduce**
1. Start server.
2. Grab flag by holding `E`.
3. Stop holding E once the animation reaches the part where the player goes down to pick the flag up.

**Expected behavior**
The flag should not disappear if its animation has not been completed. The action of grabbing the flag should be cancelled if `E` has not been held for the full length of the animation.

**Comment by gnoriega27** [comment]
Interestingly, this bug only happens in multiplayer. When in single-player, everything works fine.

**Comment by gnoriega27** [comment]
Closed for now since we are changing the flag pickup/drop mechanism
